# Generated by Django 2.0.7 on 2018-08-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180801_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity1',
        ),
    ]
