# Generated by Django 2.0.7 on 2018-08-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
