# Generated by Django 2.1 on 2018-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
